"creation_rules":
- "age": "age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8"
  "encrypted_regex": "^(data|stringData)$"
  "mac_only_encrypted": true
  "path_regex": "gitops/.*\\.sops\\.ya?ml"
"stores":
  "yaml":
    "indent": 2
