##############################################################################
# passbolt.tf
# Reads cluster details from Passbolt and writes generated secrets back.
##############################################################################

###############################################################################
# READ — pull cluster API endpoint from Passbolt (optional)
# Only queries Passbolt when passbolt_resource_id_cluster_endpoint is set.
###############################################################################

data "passbolt_password" "cluster_endpoint" {
  count = var.passbolt_resource_id_cluster_endpoint != "" ? 1 : 0
  id    = var.passbolt_resource_id_cluster_endpoint
}

locals {
  # Use Passbolt-sourced endpoint if provided, otherwise fall back to variable
  resolved_cluster_endpoint = (
    var.passbolt_resource_id_cluster_endpoint != ""
    ? data.passbolt_password.cluster_endpoint[0].password
    : local.cluster_endpoint
  )
}

###############################################################################
# WRITE — store generated secrets back into Passbolt after bootstrap
###############################################################################

resource "passbolt_password" "talosconfig" {
  name        = "${var.cluster_name}-talosconfig"
  username    = "talosctl"
  uri         = local.cluster_endpoint
  password    = data.talos_client_configuration.this.talos_config
  description = "talosconfig for cluster ${var.cluster_name}. Generated by Terraform."

  lifecycle {
    ignore_changes = [description, password]
  }
}

resource "passbolt_password" "kubeconfig" {
  name        = "${var.cluster_name}-kubeconfig"
  username    = "kubernetes-admin"
  uri         = local.cluster_endpoint
  password    = talos_cluster_kubeconfig.this.kubeconfig_raw
  description = "kubeconfig for cluster ${var.cluster_name}. Generated by Terraform."

  lifecycle {
    ignore_changes = [description, password]
  }
}

resource "passbolt_password" "machine_secrets" {
  name        = "${var.cluster_name}-machine-secrets"
  username    = "terraform"
  uri         = local.cluster_endpoint
  password    = talos_machine_secrets.this.machine_secrets
  description = "Talos machine secrets for cluster ${var.cluster_name}. Contains cluster CA keys — keep safe."

  lifecycle {
    # NEVER overwrite — losing machine secrets permanently breaks the cluster.
    ignore_changes = all
  }
}
