domainFilters:
  - aknuk.dev
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        key: api-token
        name: cloudflare-dns-secret
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=envoy-external
fullnameOverride: cloudflare-dns
podAnnotations:
  secret.reloader.stakater.com/reload: cloudflare-dns-secret
policy: sync
provider: cloudflare
serviceMonitor:
  enabled: false
sources:
  - crd
  - gateway-httproute
triggerLoopOnEvent: true
txtOwnerId: default
txtPrefix: k8s.
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NElzMVZmbEx4RjVBUElD
        QVJQdnBqYjFwOWkva3Nick9Ic0MxUjBJSEZrClRYbElPQkN5MVdMaEJ5RlBhMWlr
        S01neDFRTGFvZ2szZlBvNDhUTmlDT3MKLS0tIDBtcWlTdVdHekxiZnNkcXNPZGRj
        dE9wVG9QZGpNQWlYWDljdXRYdVBtbzgKaoSfqrF9XBwZ+xgC3gZ9QxEzcHgm4S0K
        DDDlpOMVF0gjDxf3QBZFY11ZvMEdMMhOthVjmCfY5ApTDFD/ys0a/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T16:12:23Z"
  mac: ENC[AES256_GCM,data:yAzktqtovPekjfZQfql5PiC5C8lvImtkGG96ynatulAzLC/DHNpvfH6TjwYNLGiAm22B5ieDNDHS1BPxKyJy8B3Q4sX7YSvK2b5AtTFGB2IM5aUPdfLhBpqXfJO9OePmFh9lqayg6vztH1bRhdoouKOiXDS0EBCp77Ue8Urk+Wc=,iv:EMYLCeK7GM6UE+dxELA9kylqY8FtQKghY8cCYWYIXaU=,tag:nbReJgOPLHDGQLiv7BVdTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
