apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:vJn/PfJndwBMr9cMAmwjH1pTDJIj/S3HS0Ha9RsR9bM8Hwv7ySs2Dg==,iv:X87IYbzUztNpmHqKZ3ar7qJm7OuF6pt2LvnCmamDedk=,tag:S9qiRztofWsAbzK93ZVN6g==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnR1pnMmhraXNxZG1VSUtX
        V0FNYXorZzdpSlR4Tnd6b3ZrazBCaWlsRm5BCm9LbjY0THIwRnlZNWluQWlqSGZL
        eFZ1VnlYOWdBb1E4M1NURXU3UDNXUU0KLS0tIGNzWmFKaGVLT3V4dUdpKzdhbk9T
        UFVhNVRreWxEaGhGaGFPd084UG9hdUUKby+MKggWzoqnaxERm5xJqWRrV9VwTXxi
        bFOSjVMxxd9VZxYEVV1hf8nxk1q4JDkayY/jra3AVlZscYoXPSyscQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T16:05:51Z"
  mac: ENC[AES256_GCM,data:5u57CUD3E2Wth1J/R+iTxmfytUAz2t9HBbkMReFsEuhwpyV18uTFBIKwhKOHYQroyQKLA3DQWldlgYMFY8St5vghiEm4mGBLXWKsQqRaUy2R7o9uR5IYl6jcPSKMUMU9q/6gSvmG9reYhKvulZfr05tCjRdoBRNL+DXV4jm9n7Y=,iv:H6z8ySsiev18Grlja39K6fkZtZHV25A9Pz3DoFRO0MI=,tag:mNj7nfZodAIApehan3w6IQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
