apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:K5RMbuvXaCpz2LddeMTqfr4b1EI0xOhuFJevoDu4a49L+tHjnVYYMA==,iv:nLFu1Rhk2tOVI6Rp7zdCrlbhnE8/enQ0vytVG9w4Y1Y=,tag:J/AmFvdhdd3dKSopQBosFQ==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMkhlSEthTnBnOHBHZzNR
        OTNpeXBFb3NEekNsUkR5RmdiMlFJdFJ0UkVnCmp4cmNQbHNocmRmMmhWTy9DZHpp
        UERHeEdtcDZMOXVjWVJJVk82bEtQU0kKLS0tIHQ5WDYxL1hLN0RucnBjajdTa2RO
        eEZOSlF3ekpFbGpsbVQyUm40MXdVWGcK3vAHModbWul1tCDNf8H3vkOFG6/KfDMj
        DddMW6Cz1cm9qeyoVEUcHD8ykKhkt8ssR4+U3u35hBxttj1Hz1INJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T16:05:51Z"
  mac: ENC[AES256_GCM,data:i41w6Eu11fPh8hwOGvCjCk+HoYP5g9r87XSu1WmvZwmej8+OBtobU1PU8cp2w4KkdBEAwS/HAH0dniZbfh475hzPikTARkGhs4bQLgVt4vv6/+24y0FLFSHnbKGWPg48CZPU4DMfRTTSN4+bfNoy4pxtKDzFdy0NI5CBPRvduz4=,iv:6YVo82X+tvrju8q/IXT6ZDpjhLnRvGY4o9eD2+3uuRo=,tag:iDXzIwBs/9DrVbqSiBcWQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
