apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:hyv86yMRAYZumN67z3kHoz1a9Cr979n7/hKKoI3dBCt5r4ZBRk9MG9TxVEhUeddO9n9buqcR6T7/K7T7hUtuY+zqkT53Y7UvZPQOWdwmTauHSy0YXkf3gZKzGkVDHOVbIhrIc6t1I1ti00/lcbTsCvMkrrbnuZxyHEzfpy8vyAttQnjhOIFK1b7+J9IfZHXXHcJgitAAvcpxiuZk6NUG5I4GXazk6jdI4FtydUsNsbtMgEfs,iv:CLDJzFZVmtDR6b67+lzrvZ9yMg6KuDMtxy6l2x1Laoo=,tag:x5HILODJpiT16zWxJuFQuw==,type:str]
sops:
  age:
    - recipient: age1nekqln4rq0mqqgv650u5a7zvgdeh472phq2ckl7ufzan04qlj90q3guut8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eUxzTlB3eGp3eml6aTlY
        TWFMWWs3Ti9hZWt2R1E3S2RUcVVoUDM0V1NFClU2ODB1a2g4aFhNM2h6UTUvbHJP
        REZ4aGhpdm1udDdnVUwvdk9JSlppem8KLS0tIGY0ZEQzTFcxNit3UG85TVI1V0JW
        SE0wbG9jejlPTVltRU1MeWEwRFV3TVUKU5I14Z6ZJc95xpDWofBR4lpLQdmaFhxb
        7sR81i3hy6Vozs5zWf7BOb1yz4lmn4gjg1uoYVRUl6z0VPgeF+qd2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-18T16:05:51Z"
  mac: ENC[AES256_GCM,data:sjmMLZYWRqAW1/C0aofcvjIzjLmEknWDkCFkCY31ZXBBkEcNZuv1Ja7TnPfSIOBpUdW9sE4Kzq8PGoXpBEK+GMpB6Q+pKWkyH/Moc7YQ8lrVus08jf0a1F6hjF/Q4/mjzG1Y2hqkMbDoBshffNPITnLqHTRndCN0idiAqH1cc1I=,iv:++SsTTJJX5Tj7Bey8dz3xdVjRIryZuPGhW16gdPyr9s=,tag:LAkkxCT+hIkp1wlUWjJ2GA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
